### ISSUE TITLE
Request: Icon in Taskbar

### ISSUE THREAD

**Issue by MarcusCaepio** [vFense/vFenseAgent-win#19]
Is it possible to implement an Icon in the status bar, where the agent's status can be checked, stoped, started and restarted?

**Comment by hchac** [comment]
Hey Marcus, sorry for the long wait, we had a brief discussion about this and we decided that _at this point in time_ it doesn't seem right to spend time building a taskbar icon for our agents just to manage the service. Our agents are meant to be running all the time, and we understand that since we are in beta things get a little complicated with bugs and such, thus forcing you to manage the service by starting/stopping. But we feel that at this moment our efforts are best spent in improving the agent itself.

Do not mistake this as an outright no on the idea, we do plan on creating a taskbar icon (cross-platform) _if_ we see that it would improve the usability of the agent. However, this would have to be further down the road.

That being said, thank you for the suggestions. We greatly appreciate all feedback.
